### ISSUE TITLE
HTTP does not redirect to HTTPS

### ISSUE THREAD

**Issue by TimvdLippe** [surma/tinderforbananas.com#7]
When the page is loaded via HTTP, the user is not redirected to HTTPS even though the HTTPS version does exist.

### Reproduction steps

1. Open tinderforbananas.com/

### Expected result

User is redirected to https://tinderforbananas.com/

### Actual result

User stays on tinderforbananas.com/

**Comment by surma** [comment]
Oh, I missed that. Thanks for filing! Fixed it via Cloudflare :)
